### PR TITLE
Docs Update - 2.x - code update

### PR DESCRIPTION
**Pull request by iamacup**
The code for 2.0.0 alpha no longer worked - updated to reflect API changes and added some more descriptive messages so new users can fully understand what is happening

### CODE REVIEW

**Comment by OverHash** [comment]
I think it would be more helpful to use the `createTypeChecker` middleware when creating the definitions for the "Quick Start".

**Comment by iamacup** [comment]
To be honest mate, what I have added here is the limit of what i was able to piece together with the existing documentation - i had no idea middleware typecheckers were required? or how they work?

**Comment by OverHash** [comment]
They aren't required but definitely recommended. Essentially, you can use other packages like `@rbxts/t` to validate the type of the arguments the client sends. An example would be:
```ts
// remotes.ts
const remotes = Net.Definitions.Create({
    PrintMessage: Net.Definitions.Event<[message: string, num: number]>([createTypeChecker(t.string, t.number)])
})
```

**Comment by iamacup** [comment]
Thanks for the info, i am having trouble actually geting it to run though - can you ge your example working on 6.0.0 A6 ? This is i get with it:

```
Type 'NetMiddleware<[unknown, unknown], unknown[], Player, Player>' is not assignable to type 'NetMiddleware<[message: string, num: number], unknown[], Player, Player>'.
  Types of parameters 'next' and 'next' are incompatible.
    Types of parameters 'message' and 'args_0' are incompatible.
      Type 'unknown' is not assignable to type 'string'.ts(2322)
```

```
/* eslint-disable roblox-ts/no-any */
import Net from "@rbxts/net";
import t from "@rbxts/t";
import { createTypeChecker } from "@rbxts/net/out/middleware";

const Remotes = Net.Definitions.Create({
	PrintMessage: Net.Definitions.Event<[message: string, num: number]>([createTypeChecker(t.string, t.number)])
});

export { Remotes };
/* eslint-enable roblox-ts/no-any */
```

**Comment by OverHash** [comment]
Not sure what's going on with your version of Net. Are you sure you are using the alpha? That code worked for me.
image

**Comment by iamacup** [comment]
```
(base) MacBook-Pro-4:roblox-1 iamacup$ cat ./node_modules/@rbxts/net/package.json 
{
  "_from": "@rbxts/net@2.0.0-alpha.6",
  "_id": "@rbxts/net@2.0.0-alpha.6",
  "_inBundle": false,
  "_integrity": "sha512-6j0Ere0AIdtdY6IoPVOd1J7xeRPJJ+jlWCPhfWS03HYVtO9xfnhvHCO65MRa+c7zfepIypsIdrzXzAYYjmQuWA==",
  "_location": "/@rbxts/net",
  "_phantomChildren": {},
  "_requested": {
    "type": "version",
    "registry": true,
    "raw": "@rbxts/net@2.0.0-alpha.6",
    "name": "@rbxts/net",
    "escapedName": "@rbxts%2fnet",
    "scope": "@rbxts",
    "rawSpec": "2.0.0-alpha.6",
    "saveSpec": null,
    "fetchSpec": "2.0.0-alpha.6"
  },
  "_requiredBy": [
    "#USER",
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/@rbxts/net/-/net-2.0.0-alpha.6.tgz",
  "_shasum": "8d9739f2a27b55bfeceb8c43be8e9fc24dd4702f",
  "_spec": "@rbxts/net@2.0.0-alpha.6",
  "_where": "/Users/iamacup/Desktop/me-stuff/source/roblox-1",
  "author": "",
  "bugs": {
    "url": "https://github.com/roblox-aurora/rbx-net/issues"
  },
  "bundleDependencies": false,
  "dependencies": {},
  "deprecated": false,
  "description": "![](logo.png) Roblox Networking\r ===========",
  "devDependencies": {
    "@rbxts/compiler-types": "^1.0.0-beta.13.1",
    "@rbxts/t": "^1.3.5",
    "@rbxts/types": "^1.0.435",
    "@typescript-eslint/eslint-plugin": "^4.9.0",
    "@typescript-eslint/parser": "^4.9.0",
    "cross-env": "^7.0.3",
    "eslint": "^7.14.0",
    "eslint-config-prettier": "^6.15.0",
    "eslint-plugin-prettier": "^3.2.0",
    "eslint-plugin-roblox-ts": "0.0.24",
    "prettier": "^2.2.1",
    "rbxts-transform-debug": "^0.1.0",
    "rbxts-transform-env": "^0.3.0",
    "typescript": "^4.1.2"
  },
  "homepage": "https://github.com/roblox-aurora/rbx-net#readme",
  "keywords": [],
  "license": "MIT",
  "main": "out/init.lua",
  "name": "@rbxts/net",
  "publishConfig": {
    "access": "public",
    "tag": "alpha"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/roblox-aurora/rbx-net.git"
  },
  "scripts": {
    "build": "cross-env NODE_ENV=production TYPE=ts rbxtsc --verbose",
    "build:dev": "cross-env NODE_ENV=development TYPE=ts rbxtsc --verbose",
    "build:example": "cross-env NODE_ENV=development TYPE=ts rbxtsc-dev --type=game -p ./example -i ./include",
    "prepare": "npm run build",
    "serve:example": "rojo serve ./example/default.project.json --port 34567",
    "watch:example": "cross-env NODE_ENV=development TYPE=ts rbxtsc-dev -w --type=game -p ./example -i ./include"
  },
  "types": "out/index.d.ts",
  "version": "2.0.0-alpha.6"
}

```

Are you sure you are using alpha.6? when i tried to install it first it installed `2.0.0-indev.9` which i had to manually fix.

I do have a comment on the 2.0.0 issue about how master is out of sync with NPM, which could also be causing his

**Comment by OverHash** [comment]
I'm definitely on 2.0.0!
<details>
<summary>package.json for net</summary>

```json
{
  "_from": "@rbxts/net@2.0.0-alpha.6",
  "_id": "@rbxts/net@2.0.0-alpha.6",
  "_inBundle": false,
  "_integrity": "sha512-6j0Ere0AIdtdY6IoPVOd1J7xeRPJJ+jlWCPhfWS03HYVtO9xfnhvHCO65MRa+c7zfepIypsIdrzXzAYYjmQuWA==",
  "_location": "/@rbxts/net",
  "_phantomChildren": {},
  "_requested": {
    "type": "version",
    "registry": true,
    "raw": "@rbxts/net@2.0.0-alpha.6",
    "name": "@rbxts/net",
    "escapedName": "@rbxts%2fnet",
    "scope": "@rbxts",
    "rawSpec": "2.0.0-alpha.6",
    "saveSpec": null,
    "fetchSpec": "2.0.0-alpha.6"
  },
  "_requiredBy": [
    "#USER",
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/@rbxts/net/-/net-2.0.0-alpha.6.tgz",
  "_shasum": "8d9739f2a27b55bfeceb8c43be8e9fc24dd4702f",
  "_spec": "@rbxts/net@2.0.0-alpha.6",
  "_where": "/mnt/c/Users/OverHash/Desktop/yoyo-simulator",
  "author": "",
  "bugs": {
    "url": "https://github.com/roblox-aurora/rbx-net/issues"
  },
  "bundleDependencies": false,
  "dependencies": {},
  "deprecated": false,
  "description": "![](logo.png) Roblox Networking\r ===========",
  "devDependencies": {
    "@rbxts/compiler-types": "^1.0.0-beta.13.1",
    "@rbxts/t": "^1.3.5",
    "@rbxts/types": "^1.0.435",
    "@typescript-eslint/eslint-plugin": "^4.9.0",
    "@typescript-eslint/parser": "^4.9.0",
    "cross-env": "^7.0.3",
    "eslint": "^7.14.0",
    "eslint-config-prettier": "^6.15.0",
    "eslint-plugin-prettier": "^3.2.0",
    "eslint-plugin-roblox-ts": "0.0.24",
    "prettier": "^2.2.1",
    "rbxts-transform-debug": "^0.1.0",
    "rbxts-transform-env": "^0.3.0",
    "typescript": "^4.1.2"
  },
  "homepage": "https://github.com/roblox-aurora/rbx-net#readme",
  "keywords": [],
  "license": "MIT",
  "main": "out/init.lua",
  "name": "@rbxts/net",
  "publishConfig": {
    "access": "public",
    "tag": "alpha"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/roblox-aurora/rbx-net.git"
  },
  "scripts": {
    "build": "cross-env NODE_ENV=production TYPE=ts rbxtsc --verbose",
    "build:dev": "cross-env NODE_ENV=development TYPE=ts rbxtsc --verbose",
    "build:example": "cross-env NODE_ENV=development TYPE=ts rbxtsc-dev --type=game -p ./example -i ./include",
    "prepare": "npm run build",
    "serve:example": "rojo serve ./example/default.project.json --port 34567",
    "watch:example": "cross-env NODE_ENV=development TYPE=ts rbxtsc-dev -w --type=game -p ./example -i ./include"
  },
  "types": "out/index.d.ts",
  "version": "2.0.0-alpha.6"
}
```

</details>

I'm very confused why it works for me, and not for you then..

**Comment by iamacup** [comment]
OK well i suggest it is merged as-is - given that it replaces an empty page with something useful - and if you want to change after - feel free :)

**Comment by Vorlias** [comment]
Thanks for adding to the documentation, it's much appreciated.

**Pull request merged**
